# -*- coding: utf-8 -*-
"""Advent Challenge D11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SmjAN83YG2XbXsbEAMcjI_blcCtM3Uk
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Advent 2024/day11/d11_input.txt'

import numpy as np
import pandas as pd

"""##--- Day 11: Plutonian Pebbles ---

The ancient civilization on Pluto was known for its ability to manipulate spacetime, and while The Historians explore their infinite corridors, you've noticed a strange set of physics-defying stones.

At first glance, they seem like normal stones: they're arranged in a perfectly straight line, and each stone has a number engraved on it.

The strange part is that every time you blink, the stones change.

Sometimes, the number engraved on a stone changes. Other times, a stone might split in two, causing all the other stones to shift over a bit to make room in their perfectly straight line.

As you observe them for a while, you find that the stones have a consistent behavior. Every time you blink, the stones each simultaneously change according to the first applicable rule in this list:

If the stone is engraved with the number 0, it is replaced by a stone engraved with the number 1.
If the stone is engraved with a number that has an even number of digits, it is replaced by two stones. The left half of the digits are engraved on the new left stone, and the right half of the digits are engraved on the new right stone. (The new numbers don't keep extra leading zeroes: 1000 would become stones 10 and 0.)
If none of the other rules apply, the stone is replaced by a new stone; the old stone's number multiplied by 2024 is engraved on the new stone.
No matter how the stones change, their order is preserved, and they stay on their perfectly straight line.

How will the stones evolve if you keep blinking at them? You take a note of the number engraved on each stone in the line (your puzzle input).

If you have an arrangement of five stones engraved with the numbers 0 1 10 99 999 and you blink once, the stones transform as follows:

The first stone, 0, becomes a stone marked 1.
The second stone, 1, is multiplied by 2024 to become 2024.
The third stone, 10, is split into a stone marked 1 followed by a stone marked 0.
The fourth stone, 99, is split into two stones marked 9.
The fifth stone, 999, is replaced by a stone marked 2021976.
So, after blinking once, your five stones would become an arrangement of seven stones engraved with the numbers 1 2024 1 0 9 9 2021976.

Here is a longer example:

Initial arrangement:
125 17

After 1 blink:
253000 1 7

After 2 blinks:
253 0 2024 14168

After 3 blinks:
512072 1 20 24 28676032

After 4 blinks:
512 72 2024 2 0 2 4 2867 6032

After 5 blinks:
1036288 7 2 20 24 4048 1 4048 8096 28 67 60 32

After 6 blinks:
2097446912 14168 4048 2 0 2 4 40 48 2024 40 48 80 96 2 8 6 7 6 0 3 2
In this example, after blinking six times, you would have 22 stones. After blinking 25 times, you would have 55312 stones!

Consider the arrangement of stones in front of you. How many stones will you have after blinking 25 times?

write functions
1. if num == 0: new_num = 1
2. if num is even and has 2 digits: new_num_1 = num[len(num)//2:] and new_num_2 = num[:len(num)//2]. extra leading 0's are removed if applies.
3. if num is odd, new_num = num*2024
"""

def is_even_num_digits(num): #here!
  num = len(num)
  if num % 2 == 0:
    return True
  else:
    return False

def identify_function(list_strings):
  new_nums = []
  for i, num in enumerate(list_strings):
    # print('i', i, 'num', num)
    if num == '0':
      new_num = '1'
      new_nums.append(new_num)

    elif is_even_num_digits(num): # and has 2 digits? :
      new_num_a = num[:len(num)//2]
      new_num_b = num[len(num)//2:]
      for new_num in [new_num_a, new_num_b]:
        # print('new_num_b',new_num_b)

        while new_num[0] =='0' and len(new_num)>1:       # extra leading 0's are removed if len(new_num)>1.
          new_num = new_num[1:] #remove last digit if = 0
          # print('new_num',new_num)
        new_nums.append(new_num)
    else: #is odd
      new_num = str(int(int(num)*2024))
      new_nums.append(new_num)
  return new_nums



data_str_a = """0 1 10 99 999"""
nums = data_str_a.split(" ")
nums

print(nums)
# after 1 blink 5 becomes 7 stones: 1 2024 1 0 9 9 2021976.
stones = identify_function(nums)
print(stones)
print(f'num of stones:', len(stones))
# 3. if num is odd, new_num = num*2024

def num_arrangements(integer,nums):
    print('input', nums)
    # stones = identify_function(nums)
    i = 0
    # print(1, 'blinks, ', len(stones), f'stones:', stones)

    while i!= integer-1:
      stones = identify_function(nums)
      # print(i, 'blinks, ',len(stones), f'stones:', stones)

      for i in range(1, integer):
        stones = identify_function(stones)
        # print(i, 'blinks, ',len(stones), f'stones:', stones)

    return len(stones)

# Initial arrangement:
data_str_b = """125 17"""
nums = data_str_b.split(" ")

# num_arrangements(6, nums) #22
num_arrangements(25, nums) #55312

# After 1 blink:  253000 1 7
# After 2 blinks: 253 0 2024 14168
# After 3 blinks: 512072 1 20 24 28676032
# After 4 blinks: 512 72 2024 2 0 2 4 2867 6032
# After 5 blinks: 1036288 7 2 20 24 4048 1 4048 8096 28 67 60 32
# After 6 blinks: 2097446912 14168 4048 2 0 2 4 40 48 2024 40 48 80 96 2 8 6 7 6 0 3 2
# In this example, after blinking six times, you would have 22 stones. After blinking 25 times, you would have 55312 stones!

"""##part 1 real"""

#Consider the arrangement of stones in front of you. How many stones will you have after blinking 25 times?
data_str_real = """0 7 6618216 26481 885 42 202642 8791"""
nums = data_str_real.split(" ")
num_arrangements(25, nums) #213625

"""##part 2

--- Part Two ---
The Historians sure are taking a long time. To be fair, the infinite corridors are very large.

How many stones would you have after blinking a total of 75 times?
"""

def is_even_num_digits(num):
    return len(str(num)) % 2 == 0

def identify_function(stones_dict): # takes in dict now
    new_stones_dict = {}
    for num_str, count in stones_dict.items(): # iterate through dictionary
        num = int(num_str) #convert to int
        if num == 0:
            new_stones_dict.setdefault(1, 0) #set default if not in dict
            new_stones_dict[1] += count
        elif is_even_num_digits(num):
            half = len(str(num)) // 2
            first = int(str(num)[:half])
            second = int(str(num)[half:])
            new_stones_dict.setdefault(first, 0) #if exists increment counts, else create key
            new_stones_dict[first] += count
            new_stones_dict.setdefault(second, 0)
            new_stones_dict[second] += count
        else:
            new_num = num * 2024
            new_stones_dict.setdefault(new_num, 0)
            new_stones_dict[new_num] += count
    return new_stones_dict

def num_arrangements(integer, nums):
  # nums = list of initial stones as input
    stones_dict = {}
    for n in nums: #executes through each num in the input list (8 with this input)
        stones_dict.setdefault(int(n), 0)
        stones_dict[int(n)] +=1
    for _ in range(integer): #iterate through integer times for all inputs at the same time!
        stones_dict = identify_function(stones_dict) #transform and update the current stones_dict

    return sum(stones_dict.values()) #return total number of stones after the given number of steps.


data_str_real = """0 7 6618216 26481 885 42 202642 8791"""
nums = data_str_real.split(" ")
print(num_arrangements(75, nums)) # Output: 252442982856820